name: solarized_twitter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_twitter_api: ^0.5.4
  google_fonts: ^2.1.1
  url_launcher: ^6.0.17
  flutter_hooks: ^0.18.1
  hooks_riverpod: ^1.0.0
  flutter_signin_button: ^2.0.0
  oauth1: ^1.0.4
  shared_preferences: ^2.0.11

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
